version: "3.8"

volumes:
  esdata:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:${ELASTIC_PASSWORD} http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kib
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      # Kibana must NOT use the 'elastic' user.
      # Use a service account token instead:
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${KIBANA_SA_TOKEN}
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q '\"state\":\"green\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.13.4
    container_name: apm
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8200:8200"
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8200/ | grep -q 'APM Server' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
